spring:
  application:
    name: indicaAI

  datasource:
    url: jdbc:postgresql://localhost:5432/indicaAI_bd
    username: postgre
    password: postgre
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: true
    repair-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

