openai:
  api-key: {$OPENAIKEY}
tmdb:
  api:
    key: 30fbeb3d95ad48fcda0cf4224f317023
    url: https://api.themoviedb.org/3
spring:
  application:
    name: indicaAI

  datasource:
    url: jdbc:postgresql://localhost:5432/indicaAI_bd
    username: postgre
    password: postgre
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: true
    repair-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

